spring.application.name=citas

server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://localhost:5455/cita_db
spring.datasource.username=postgres
spring.datasource.password=Kinect1593

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true